
# Result codes for the application
SUCCESS = 0
INVALID_ARGUMENT = 1
INVALID_LOCATION = 2
FAILED_TO_CREATE_DESTINATION = 3
SSH_ERROR = 4
BAD_JOBS = 5
CLEAN_FAILED = 6
INVALID_JOB = 7
UNEXPECTED_ERROR = 8
RSYNC_FAILED = 9